@startuml

[*] --> ReadNewCmd

ReadNewCmd  ---> SendVersion : "stm --version"
SendVersion ---> ReadNewCmd
ReadNewCmd  ---> TurnOnLed : "stm led --on"
TurnOnLed ---> ReadNewCmd
ReadNewCmd ----> TurnOffLed : "stm led --off"
TurnOffLed ---> ReadNewCmd
ReadNewCmd ---> SendLedStatus : "stm get --led"
SendLedStatus ----> ReadNewCmd

@enduml